### ISSUE TITLE
xFileUpload is not available as a resource

### ISSUE THREAD

**Issue by gardym** [PowerShell/xPSDesiredStateConfiguration#146]
After installing the module xFileUpload does not appear in Get-DscResource. When present the Configuration fails with:

Undefined DSC resource 'xFileUpload'. Use Import-DSCResource to import the resource.

(Version 3.10.0.0 from the PowerShell Gallery)

**Comment by Dan1el42** [comment]
I've recently noticed this problem too. It seems that all composite resources in the xPSDesiredStateConfiguration DSC resource module like xFileUpload, xGroupSet, xProcessSet, etc. are affected, probably since they have been merged from the In-Box resource module.

I will take this issue and submit a PR for review and consideration by the PowerShell DSC team. The fix is to renamed the folders and files of the individual composite resources (e.g. removal of the MSFT_ prefix), and updates of existing unit / integration tests.

**Comment by Dan1el42** [comment]
PR #209 submitted.
