### ISSUE TITLE
xRemoteFile is not idempotent

### ISSUE THREAD

**Issue by rdean716** [PowerShell/xPSDesiredStateConfiguration#15]
During testing we noticed that remote resources were being downloaded each time the configuration is applied.  We debugged the issue back to the location in which the resource is caching the remote resources metadata for later comparison, "$env:ProgramData\Microsoft\Windows\PowerShell\Configuration\BuiltinProvCache\MSFT_xRemoteFile", by default.  The LCM can write to that path during the initial application of a configuration, but cannot read from it during subsequent applications, causing the resources to be downloaded again.  Changing the path to almost anything else works in our testing. In fact removing BuiltinProvCache and replacing it with any other value will work as well.

**Comment by KarolKaczmarek** [comment]
I'm assuming you are using Start-DscConfiguration during your testing. If that's the case, this behavior is by design, because BuiltinProvCache is being cleaned every time Start-DscConfiguration is called. As a result, every time you apply the configuration manually (using Start-DscConfiguration), cache is not present and remote resources will be downloaded. 

Main purpose of the cache is to not download resources every time the consistency engine is being run. When the configuration is being reapplied because of consistency engine kicking in, cache is not being cleared and xRemoteResource will find that given resource has been downloaded already and will not download it again.

**Comment by rdean716** [comment]
Thanks for the quick reply.  Yes, we were using Start-DscConfiguration to test.  I guess I should be using Update-DscConfiguration to  force a consistency check on WMF5?

A couple of additional question: 
BuiltinProvCache - is that a special thing?  Why did the resource behave differently when I changed the path to something that does not include BuiltinProvCache?  

I also noticed that the xArchive resource using a path that includes BuiltinProvCache was well; however, it defaults to \windows\system32\configuration\BuiltinProvCache\.  During my testing I changed the xRemoteFile module to use the same path and the resource behaved as it did when I changed the resource to use an arbitrary value.  Should that be expected?

Any additional information you can share would be great.

**Comment by KarolKaczmarek** [comment]
Usually there's no need to manually force consistency engine to run, but for testing purposes you can achieve it by calling the cim method directly:

```Invoke-CimMethod -Namespace  root/Microsoft\windows/DesiredStateConfiguration -Cl MSFT_DSCLocalConfigurationManager -Method PerformRequiredConfigurationChecks -Arguments @{Flags = [System.UInt32]1} ```

BuiltinProvCache is a special directory for cache for all resources and is being cleaned automatically. If you change it to some other location, DSC engine will not clean it up (which can be good thing for cases when you don't want to have cache cleaned when calling Start-DscConfiguration).

**Comment by rdean716** [comment]
Got it.  Thanks again for the quick feedback.
