### ISSUE TITLE
Question about xRemoteFile and Invoke-WebRequest

### ISSUE THREAD

**Issue by cdituri** [PowerShell/xPSDesiredStateConfiguration#202]
Is there any specific reason Invoke-WebRequest was chosen to back the implementation of xRemoteFile and, if not, would the team welcome the transition to an implementation using, for instance, the System.Net.WebClient class? or would a new resource, say, xWebClient, be more appropriate for something like this?

Performance is what prompted my questioning: we're using xRemoteFile to download 10s of GBs of data to endpoints and Invoke-WebRequest has been much less performant for large file transfer.

**Comment by PlagueHO** [comment]
I'm not aware of any specific reason why we're using Invoke-WebRequest over System.Net.WebClient.

However I think the use of built in PS cmdlets is always preferred over .NET classes or other methods. Now that PS is open sourced it might be worth actually looking into any performance difference between IWR and System.Net.WebClient and looking at improving the IWR performance. I'm sure the PS community will be happy to look into these sorts of things, so it might be worth logging the issue over in the PS Github repo (https://github.com/powershell/powershell/).

Failing that though:
IMHO it might be a bit of a pain having to support/manage another remote file download resource just to be able to use the WebClient class. It might be a better idea to just have a "Method" parameter on the xRemoteFile that allows the use of System.Net.WebClient rather than IWR. The "Method" could default to IWR, so that any existing users won't be affected, but you could use the alternate method where it made sense.

Also, I can see this resource being extended to support BITS as well, so a "method" parameter might not be a bad idea.

Just my 2c

**Comment by Zuldan** [comment]
BITS support would be good but I don't know if it would work in DSC. I've never been able to get it working outside of a logged in session (EG remoting or scheduled task). It's worth investigating though.

**Comment by PlagueHO** [comment]
@Zuldan - MSFT made some changes to the BITS cmdlets in WMF5.1 - I wonder if that would help?

I'm not too worried about the BITS though - it would just be "nice to have" for me mostly - but others might use it more.

But as PS is open sources we might have better luck at tracking down issues (more eyes on the code etc). Who knows :smile:

**Comment by Zuldan** [comment]
You're right, it would just be a nice to have. That's the beauty of PS being open source now. Customers can go investigate the issue directly without having to wait for Microsoft ;-) Awesome.

**Comment by iainbrighton** [comment]
BITS doesn't like authenticated proxies (from my experience). That shouldn't preclude it from being an option though!

**Comment by Dan1el42** [comment]
Not sure if you know that the PowerShell DSC team wants to move the functionality of xRemoteFile into the File resource which is unfortunately closed-source as per the [HQRM plan](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/HighQualityResourceModulePlan.md#open-source-resources-not-moving-to-hqrm) for this module. I don't know when this will happen. May be @kwirkykat can give us an idea of timelines?

**Comment by cdituri** [comment]
@PlagueHO - thanks for your response. Great point regarding the implementation of ``IWR`` direct now that Powershell is open-source; I hadn't even considered that! The suggestion on having a "method" attribute makes sense.

@Dan1el42 - most excellent point regarding the HQRM status of the File resource. Will await an official response.

@Zuldan @iainbrighton - thank you both for your input as well.

**Comment by kwirkykat** [comment]
@Dan1el42 I don't have any current or future plans surrounding File/RemoteFile/FileUpload at the moment. 

I would open-source File now if I could, but it's actually built directly into DSC/Windows unlike other resources which are "script" (Get/Test/Set), class, or composite resources with editable code.

If you guys would like to start a new xFile resource here in xPSDSC (that perhaps just uses New-Item, Remove-Item, etc.) and also combines xRemoteFile and/or xFileUpload, I would consider including that resource in the HQRM.

**Comment by PlagueHO** [comment]
@cdituri - no worries! @Dan1el42 - good point about the File resource.

So @kwirkykat - if there are no plans around combining File/RemoteFile/FileUpload at the moment, could we just keep them separate? At least for now.

I don't see the benefit in combining these resources into a single resource (especially not xFileUpload).

**Comment by Dan1el42** [comment]
@PlagueHO and @kwirkykat  Do you think it would be worth our time to rewrite the composite resource xFileUpload as normal script resource (Get-/Set- and Test-... functions) in the interim?

**Comment by PlagueHO** [comment]
@Dan1el42 - personally, I'm ok with rewriting the xFileUpload as a script based resource - assuming of course we included full unit/integration tests with it :grinning:

**Comment by kwirkykat** [comment]
@PlagueHO Sure. No plans for these resources right now. I won't be touching them.

@Dan1el42 That would be a great idea! I'm not really sure why it was wrapped in a Script resource inside a configuration to begin with...

**Comment by johlju** [comment]
This issue has been open for a long time, and it seems that it led to no work (yet). I'm closing this issue and if someone in the community want to work on any of this, then please open a new issue (resource proposal or enhancement).
