### ISSUE TITLE
Unregister Nodes from Pull Server

### ISSUE THREAD

**Issue by mycjme** [PowerShell/xPSDesiredStateConfiguration#203]
Please provide functionality to remove/unregister nodes from a Pull Server.

**Comment by dragon788** [comment]
@mycjme I think you basically have to write a new local configuration that tells them to stop talking to the server, since the periodic check-ins all happen client side. You can push this config change from any machine/account that has Administrator access to the client machines.

The nuclear option in this case might be to change the configuration ID/registration key so they no longer trust the server, but this also requires you to update all the DSC LCM instances that you do want to keep talking to the server with a new registration key, so you aren't saving yourself any work.

Scripting with PowerShell and regular expressions is probably the easiest way to update this, and doesn't require DSC to manage.

**Comment by mycjme** [comment]
I was thinking more housekeeping, in a scenario where the pull clients have already been deleted or will be rebuilt. Neither option seems feasible in this scenario

**Comment by dragon788** [comment]
In that case I believe the devices.mdb could be queried for machines that
aren't responding or haven't pulled in a while, but I'm not sure the
process for cleaning that up as I'm just getting to the point of rolling
out the pull server config to additional hosts myself.

**Comment by ArieHein** [comment]
@kwirkykat This isn't something the community can help with. The REST API for the pull server needs to implement a Remove method, and add a new cmdlets - Remove-DSCNode (param) to be able to remove a node and its matching history...but that's so core that I think its something you should be doing.

**Comment by kwirkykat** [comment]
@mycjme @dragon788 @ArieHein I'll open this issue on the DSC internal side.

**Comment by johlju** [comment]
If this isn't supported in the latest version of the Windows Server Pull Server then this will probably not be added. See [Windows Pull Server Planning Update – April 2018](https://blogs.msdn.microsoft.com/powershell/2018/04/19/windows-pull-server-planning-update-april-2018/).

Closing this issue as not fixed.
