### ISSUE TITLE
xGroup: The property 'Count' cannot be found on this object

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xPSDesiredStateConfiguration#232]
xPSDesiredStateConfiguration v3.13.0.0

When trying to add a domain security group to a empty local security group I get "The property 'Count' cannot be found on this object. Verify that the property exists.". I'm pretty sure this is a bug. Maybe a test for this situation is needed for this as well when it's fixed?

```
VERBOSE: [LABSERVER01]: LCM:  [ Start  Resource ]  [[xGroup]WSUSAdministratorsGroup]
VERBOSE: [LABSERVER01]: LCM:  [ Start  Test     ]  [[xGroup]WSUSAdministratorsGroup]
VERBOSE: [LABSERVER01]:                            [[xGroup]WSUSAdministratorsGroup] A group with the name WSUS Administrators exists.
VERBOSE: [LABSERVER01]:                            [[xGroup]WSUSAdministratorsGroup] Resolving LAB\WSUSAdmins in the LAB domain.
VERBOSE: [LABSERVER01]:                            [[xGroup]WSUSAdministratorsGroup] Property Members. The number of provided unique group members 1 is different from the number of actual group members 0.
VERBOSE: [LABSERVER01]: LCM:  [ End    Test     ]  [[xGroup]WSUSAdministratorsGroup]  in 5.9150 seconds.
VERBOSE: [LABSERVER01]: LCM:  [ Start  Set      ]  [[xGroup]WSUSAdministratorsGroup]
VERBOSE: [LABSERVER01]:                            [[xGroup]WSUSAdministratorsGroup] Performing the operation "Set" on target "Group: WSUS Administrators".
VERBOSE: [LABSERVER01]:                            [[xGroup]WSUSAdministratorsGroup] Resolving LAB\WSUSAdmins in the LAB domain.
Invoke-CimMethod : The property 'Count' cannot be found on this object. Verify that the property exists.
```

**Comment by Zuldan** [comment]
Some more info. In the resource config, if I replace 'Members' with 'MembersToInclude' then the resource works perfectly, the domain security group is added to the empty local security group.

**Comment by jmpetty21** [comment]
This still appears to be an issue in 4.0.0.0

**Comment by PlagueHO** [comment]
@Zuldan, @jmpetty21 - could you possibly post your a copy of the config for the step that is failing?

**Comment by kwirkykat** [comment]
@Zuldan @PlagueHO Can you try this with the current version (4.0.0.0)? This should be fixed now. There was a lot of clean-up in Group for PSDscResources and the code sections on Members was re-worked quite a bit.

**Comment by jmpetty21** [comment]
I apologize for the delay in responses. I am re running everything now and will post shortly.

**Comment by jmpetty21** [comment]
Configuration TEST{
    Import-DscResource -ModuleName xPSDesiredStateConfiguration
            xgroup administrator{
            Ensure = 'Present' 
            GroupName = "Administrators"
            Members = "Domain\Group"
       }
}

Here is the output from running Update-DSCConfiguration -wait -verbose on the client machine (set to pull)
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfigu
ration'.
VERBOSE: An LCM method call arrived from computer 2016GUI01 with user sid S-1-5-21-3913399748-2787938377-331065898-36710.
VERBOSE: [2016GUI01]:                            [] Executing Get-Action with configuration (null)'s checksum: 0941AAE4247DC3EA7F5E50094A4169F9FA6B87F53B7170CB77D1989198FF2932.
VERBOSE: [2016GUI01]:                            [] Executing Get-Action with configuration 's checksum returned result status: GetConfiguration.
VERBOSE: [2016GUI01]:                            [] Checksum is different. LCM will execute GetConfiguration to pull configuration .
VERBOSE: [2016GUI01]:                            [] Executing GetConfiguration succeeded. Configuration  was pulled from server.
VERBOSE: [2016GUI01]:                            [] Applying the new configuration(s) pulled.
VERBOSE: [2016GUI01]: LCM:  [ Start  Resource ]  [[xGroup]administrator]
VERBOSE: [2016GUI01]: LCM:  [ Start  Test     ]  [[xGroup]administrator]
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] A group with the name Administrators exists.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Group\Domain with domain trust.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Property Members. The number of provided unique group members 1 is different from the number of actual group members 4.
VERBOSE: [2016GUI01]: LCM:  [ End    Test     ]  [[xGroup]administrator]  in 2.9220 seconds.
VERBOSE: [2016GUI01]: LCM:  [ Start  Set      ]  [[xGroup]administrator]
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Performing the operation "Set" on target "Group: Administrators".
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Administrator as a local account.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Group1 in the Domain domain.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Domain Admins in the MAIN domain.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Group2 in the Domain domain.
VERBOSE: [2016GUI01]:                            [[xGroup]administrator] Resolving Domain\Group with domain trust.
The property 'Count' cannot be found on this object. Verify that the property exists.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
    + PSComputerName        : 2016gui01
 
VERBOSE: [2016GUI01]: LCM:  [ End    Set      ]  [[xGroup]administrator]  in 0.4690 seconds.
The PowerShell DSC resource '[xGroup]administrator' with SourceInfo '::5::9::xgroup' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : 2016gui01
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : 2016gui01
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 5.067 seconds

**Comment by kwirkykat** [comment]
@jmpetty21 Ah. I think I see the issue in the resource. 😢 If you put the members in an array instead, does it work?

```powershell
Configuration TEST{
   Import-DscResource -ModuleName xPSDesiredStateConfiguration
    xgroup administrator{
        Ensure = 'Present' 
        GroupName = "Administrators"
        Members = @( "Domain\Group" )
    }
}
```

**Comment by jmpetty21** [comment]
Get the exact same result

**Comment by PlagueHO** [comment]
Thanks @jmpetty21 - I'll try and dig into this tomorrow night.

**Comment by kwirkykat** [comment]
@jmpetty21 You may still have an older version of xPSDesiredStateConfiguration installed on your machine because one of the verbose messages above was edited slightly in 4.0.0.0 but it's still the old version in the output you gave above:

(Your output)
VERBOSE: [2016GUI01]: [[xGroup]administrator] Property Members. The number of provided unique group members 1 is different from the number of actual group members 4.

(What the new version 4.0.0.0 would have output)
VERBOSE: [2016GUI01]: [[xGroup]administrator] The number of provided unique group members 1 in Administrators is different from the number of actual group members 4.

You can check which version(s) you have installed by calling Get-DscResource xGroup
My guess is that you actually have 2 or more versions installed. DSC will still pick the old one *even if you specify that you want to import the new version*. Yes, this is a bug in DSC.

I'm not sure if you need to completely uninstall all the versions or just remove them from your PowerShell session, but you will have to use ```Remove-Module``` or ```Uninstall-Module``` to remove all versions of the module and then use ```Install-Module``` or ```Import-Module``` to re-install/import.

**Comment by jmpetty21** [comment]
@kwirkykat @PlagueHO Sorry for the delay. I was on a mini vacation.

I ran Get-DscResource xgroup and below is the output. It is showing only 1 version of xPSDesiredStateConfiguration installed. 

PS C:\Users\me\Documents> Get-DscResource xgroup

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
PowerShell      xGroup                    xPSDesiredStateConfiguration   4.0.0.0    {GroupName, Credential, DependsOn, Description...}

I have uninstalled the module and reinstalled. 
Now I am getting a different error message

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer 2016-GUI with user sid S-1-5-21-3913399748-2787938377-331065898-36710.
VERBOSE: [2016-GUI]: LCM:  [ Start  Set      ]
VERBOSE: [2016-GUI]: LCM:  [ Start  Resource ]  [[xGroup]administrator]
VERBOSE: [2016-GUI]: LCM:  [ Start  Test     ]  [[xGroup]administrator]
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] A group with the name Administrators exists.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving Domain\AdminGroup with domain trust.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving LocalAdmin as a local account.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Property Members. The number of provided unique group members 2 is different from the number of actual group members 4.
VERBOSE: [2016-GUI]: LCM:  [ End    Test     ]  [[xGroup]administrator]  in 0.1720 seconds.
VERBOSE: [2016-GUI]: LCM:  [ Start  Set      ]  [[xGroup]administrator]
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Performing the operation "Set" on target "Group: Administrators".
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving Seadmin as a local account.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving Domain Admins in the DOMAIN domain.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving ITWSA-Administrators in the DOMAIN domain.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving dbaadmin in the DOMAIN domain.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving DOMAIN\AdminGroup  with domain trust.
VERBOSE: [2016-GUI]:                            [[xGroup]administrator] Resolving LocalAdmin as a local account.
Cannot bind argument to parameter 'MembersAsPrincipals' because it is an empty array.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyArrayNotAllowed,Add-GroupMembers
    + PSComputerName        : localhost
 
VERBOSE: [2016-GUI]: LCM:  [ End    Set      ]  [[xGroup]administrator]  in 0.2340 seconds.
The PowerShell DSC resource '[xGroup]administrator' with SourceInfo '::6::9::xgroup' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [2016-GUI]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.641 seconds

**Comment by jmpetty21** [comment]
Sorry, here is the configuration
Configuration Lab{

Import-DscResource -ModuleName xPSDesiredStateConfiguration

    
        xgroup administrator{
            Ensure = 'Present' 
            GroupName = 'Administrators'
            Members = @('Domain\AdminGroup','LocalAdmin')
        
    }
}

**Comment by kwirkykat** [comment]
@jmpetty21 I figured out where the confusion was here (it was all me, sorry).

We recently released the new module PSDscResources which contains the Group resource. The problem you are describing has been fixed there.
The code from that Group resource was merged into xGroup here as well.
However, we didn't release xPSDesiredStateConfiguration again after that code was merged, but we *did* release PSDscResources with the fixed code.
My bad. I was under the assumption we had released the fixed code here as well.

The good news is we just did another release today, so the new xPSDesiredStateConfiguration (5.0.0.0), should contain the fix you are looking for.
Group in PSDscResources also contains this fix.

**Comment by jmpetty21** [comment]
Great news! I will give it a try tomorrow morning.

**Comment by jmpetty21** [comment]
@kwirkykat 5.0.0.0 is working great! thanks for your assistance.

**Comment by LiamFisher92** [comment]
@kwirkykat, could you close this issue pls? 😛
