### ISSUE TITLE
UseUpToDateSecuritySettings in MSFT_xDSCWebService should be required 

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xPSDesiredStateConfiguration#247]
Since not specifying $true can potentially leave the machine in a less secure state.  The property should be required in order to ensure the user wants either the secure or less secure state.

**Comment by TravisEz13** [comment]
This is related to #223

**Comment by TravisEz13** [comment]
We should rename the property to `EnforceSecurityBestPractices` in order to avoid future breaking changes and add an optional property to disable this such as `RequireSecureCommunicationProtocols'

**Comment by narrieta** [comment]
Per discussion offline the property will be renamed to EnforceSecurityBestPractices and made mandatory.

**Comment by kwirkykat** [comment]
On further discussion, we should add a single property named 'SecurityBestPractices' that takes an array of string values specifying which practices to enable. One of these values should be 'All' to indicate that all possible best practices should be enabled. Another value should be 'SecureTLSProtocols' to indicate the current practice that can be enabled.

**Comment by BerheAbrha** [comment]
I have similar idea to Katie. In DSC Signature validation could be turned on/off for specific DSC artifacts. we can use similar schema for the resource here:- 
 
	[Description ("The Security Best practice to apply on the machine.."),
	ValueMap{"TLS", "Foo"},Values{"TLS", "Foo"}]
	string SecurityBestPractice[];

**Comment by Indhukrishna** [comment]
_Final Design_
[required, Description("This property will ensure that the Pull Server is created with the most secure practices")] 
  boolean UseSecurityBestPractices;
 [write,ValueMap{"SecureTLSProtocols"},Values{"SecureTLSProtocols"}] string DisableSecurityBestPractices;

While this issue is being fixed, it will also be good to have a document that explains what each of the values in DisableSecurityBestPractices mean. For now, it is only SecureTLSProtocols.

**Comment by kwirkykat** [comment]
Closed by #261
