### ISSUE TITLE
Update xGroup to have a different key

### ISSUE THREAD

**Issue by DamianBis** [PowerShell/xPSDesiredStateConfiguration#270]
At the moment the "GroupName" is the key of xgroup.

We have the problem of i can't use xGroup twice in my config because i'm trying to add 2

use case:

We use composite resources, we have a basic config anything that has to be applied to ALL Servers goes in here.

in here we have resource

xGroup AddLocalAdminToAdministrators
{
GroupName = 'Administrators'
Ensure='Present'
MembersToInclude='CompanyAdmin'
}

One of our application servers requires a different user account be in part of the admin group. so in the config for that server it would firstly call the Server composite resource and then we would have ANOTHER resource as below

xGroup AddAppAccounttoAdministrators
{
GroupName = 'Administrators'
Ensure = 'Present'
MembersToInclude = 'ApplicationAdminAccount'
}

This will not compile because there are 2 resources with the same key.

I don't know what the solution to this would be and whether there are other people using DSC the same way or not to have this problem. I have a workaround (pass extra admin accounts through to the composite resource) but it's not as clean

**Comment by kwirkykat** [comment]
@DamianBis GroupName is the logical key for a Group so it will not be changed.

This is a limitation of all DSC resources, not just xGroup specifically.
The DSC LCM (engine) doesn't know how to deal with resource conflicts.

Imagine if we allowed you to specify to same Group twice, both with the Members property rather than MembersToInclude.
They would conflict because you were trying to specify two different states the group should be in at the same time.
Of if you specified two resources with the same group name and one had a member in MembersToExclude and the other had the same member in MembersToInclude.
The DSC LCM wouldn't know what to do.

I've asked the DSC team if there is any workaround for what you are trying to do, but these two resources cannot be defined in the same configuration.

Sorry 😞
