### ISSUE TITLE
Should document how to make client work with TLS 1.0 

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xPSDesiredStateConfiguration#272]
https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/MSFT_xDSCWebService/SecureTLSProtocols.psm1

Older clients would not connect with protocols newer than tls 1.0

**Comment by megamorf** [comment]
Windows 7 and Server 2008 R2 support TLS 1.1 and isn't WMF4/5 only available for those two and newer OS?

https://technet.microsoft.com/en-us/library/dn786419(v=ws.11).aspx

**Comment by TravisEz13** [comment]
@megamorf Even though TLS 1.1 was available on Windows 7, etc, it .NET WinHttp Client did not use it by default.  We need to include TLS 1.0 so the clients can still communicate.

**Comment by skest3qc** [comment]
This helped me a lot.
Had this issue
PullServer is 2016
TargetNode is 2008R2

Error when updating configuration:
Failed to get the action from server PullServer ... InvalidResult: (root/Microsoft/...gurationManager:String)

Eventlog:
Message One or more errors occurred. 
HResult -2146233088 
StackTrack    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PowerShell.DesiredStateConfiguration.Commands.SendDscStatusCommand.IssueRequest(HttpClient client, String subLink, ErrorRecord& errorRecord)

After enabling TLS 1.0 and rebooting the PullServer the target node was able to get its configuration

**Comment by TravisEz13** [comment]
@skest3qc Could you try updating the code?  should be a simple change.  Mention me in the PR if you do.

**Comment by EpicPhil** [comment]
I may be missing something here, but isn't the whole point of having these secure defaults are so that the pull server would be harder to compromise? Instead of weakening the pull server, can the clients not be updated to use TLS 1.1? From my reading of @TravisEz13's comment, it looks like the functionality is there, it just needs to be enabled. There is also [this update](https://support.microsoft.com/en-us/kb/3140245) to enable the protocol by default.

**Comment by TravisEz13** [comment]
I think we should have the option to enable TLS 1.0 at minimum and document the rest of what you have said.  As @skest3qc has mentioned, without this issue he would not have found a solution, and I opened the issues after working with another customer.

**Comment by johlju** [comment]
I think this is resolved since the parameter `$UseSecurityBestPractices` can be used to enable TLS 1.1 and TLS 1.2.

https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/8320ce6ce9243ec5f3753ce694675424fc34aeca/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.psm1#L24

Closing this as resolved. But if this was closed in error, then please reopen or comment!
