### ISSUE TITLE
How many agent servers that PowerShell DSC 5.1 can manage?

### ISSUE THREAD

**Issue by chancein007** [PowerShell/xPSDesiredStateConfiguration#434]
In the DSC pull report server mode, we found that after we registered more than 2000 DSC agent servers on one DSC agent report server and later we can't register new DSC agent.

How many agent servers that PowerShell DSC 5.1 can manage?

before last week, the pull server can work well but in last weekend, our pull server went down for 3 days. On this Monday, we restarted our load balance servers(1 nginx +2 DSC report server + SQL Server ( using data bridge from Access to SQL Server ). After few minutes, the Nginx server went down again.
In this case, we un-registered the DSC agent for all 2000 servers and registered again(without uninstalling the DSC pull server), however, we couldn't register again.

The error we found in DSC Windows operation log as below:
"The configured upper limit was set to 10000."

Meanwhile, the PowerShell Console showed up the below error message:

"Failed to register DSC agent with AgentID: xxxx-xxx-xxx-xxxx " which was threw by RegisterDSCAgentCommandFailed,Microsoft.PowerShell.DesiredStateConfiguration.command.registerDSCAgentCommand.

Any help is much appreciated.

**Comment by johlju** [comment]
> After few minutes, the Nginx server went down again

Have you tried without the load balancer, just to rule that out? If it the load balancer is the fault?

> The error we found in DSC Windows operation log as below: "The configured upper limit was set to 10000."

On which server did you see this error message, can you provide the entire event log entry? Obfuscate any sensitive information. 

You are not seeing any other error messages from the operating system or IIS, on either the target node or the Pull Server server?

**Comment by chancein007** [comment]
Without the load balancer, we still met this issue. We see this error on the DSC report server.

What is more, we used the windows performance monitor, we found that the active request number on the DSC pull server is always 64. Is there any way to adjust this limitation on the DSC report server side?

**Comment by johlju** [comment]
If anyone in the community have knowledge in this area, then please see if you can help out here. 

Don't have the knowledge in that area, so I don't know it that is a limit, or if the limit ca be change and if so, what the consequences (in any) could be. What performance counter are you looking at? The IIS active request counter? 

Could you provide the entire event log entry for the errors you are seeing (not just the message part)?

**Comment by ArieHein** [comment]
i think that's the limit when using the built-in driver, which is why you can now move to a SQL server driver instead.
On the more practical side, why would you use one pull server for 2000 machines ?
your hogging that pull server, I mean even with the random time added to the agent schedule so you dont get DDOS on your pull server by 2000 agents connecting at same time (+random), its not a good practice. I used to have 2 pull servers to prod and test, and 2 report servers so it matched my needs.

That said, if you do have 2-5k servers in prod for example, I would still split them to functionality or zones (like vlans for example) or move to SQL server as the backend.
