### ISSUE TITLE
Support UNC paths in xRemoteFile

### ISSUE THREAD

**Issue by JVimes** [PowerShell/xPSDesiredStateConfiguration#44]
I'd like xRemoteFile to be able to download to a UNC path.

> PowerShell DSC resource MSFT_xRemoteFile  failed to execute Set-TargetResource functionality with error message: Specified DestinationPath is not valid: "\\VBOXSVR\buildprovisioning\bin\advinst.msi". DestinationPath should be local path instead
of UNC path.

**Comment by KarolKaczmarek** [comment]
Hi,

Could you tell me what is the scenario you are trying to accomplish?

Do you want to specify UNC path on the local machine for some reason?
Or you want to specify UNC path to point DestinationPath to the remote node?

**Comment by JVimes** [comment]
Sure. I want to download from the Internet to a shared folder accessed via UNC path.

I'm in the process of converting a provisioning script to DSC. I have several VMs that share a folder. The first VM to be configured downloads some large install media to the shared folder and runs the media. Then, subsequent VMs can skip the download to save time/bandwidth. I'm using VirtualBox's shared folders, which are accessible via UNC path by default.

**Comment by ArieHein** [comment]
@JVimes: Either I'm missing something or youre not using the resource correctly.
For start, the error message should have said "\\VBOX.." so i hope thats not a mistype from your side on the DesitnationPath. Never the less the resource description states: "ensures the presence of remote files on a local machine". From my understanding, this resource would make sure a file on a share will be compared to a file on the local machine and if needed it will be downloaded localy.

Taking your example, if you download the file from the share localy to the vm and then run it from the local folder, then you can use this resource to make sure each vm will have a copy localy of the installation. Since you want to avoid that all together, if that share was on a VM of its own, as in a VM running a Windows OS, then you can use this resouce to download the installation from the web to the local folder (that has the share on it). Then from each VM you can use other commands to run the installation from that share, but theres no use for this resource in that case.

**Comment by JVimes** [comment]
The resource description can and should be changed if it makes the resource better. Supporting UNC paths would make it better. It is a reasonable use case.

The install media I'm downloading is about 4 GB, so downloading multiple times is not an option.

There was a second slash in my config, as evidenced by the error message.

**Comment by KarolKaczmarek** [comment]
The main reason UNC paths are not supported is that resource should be configuring state of the current node. We download remote file on the local machine, thus changing it's state. If we were downloading the file onto another machine, we would be changing state of the other machine instead.

The workaround for your scenario would be what @ArieHein proposed - use xRemoteFile on VM hosting the share to download remote file to the local folder (which is shared), then access it from all other VMs.

**Comment by JVimes** [comment]
If a resource finds that its state already exists, it just moves on. So the
subsequent VMs will find that the file is already in the destination and
keep going. This seems like a perfectly fine scenario for desired state
configuration. The destination state is shared between VMs, as is the
configuration.

It's unnecessarily complicated to make my script span both the VM host and
the VM's. And it's not necessary. The shared folder is conceptually part of
the guests and not the host. The host does not make use of that folder.

**Comment by ArieHein** [comment]
@JVimes: "If a resource find that its state..."  its not the resource state, its the node state. Since the share isnt on a "node" but a general share, theres no state as theres no node. If the share was on a VM running windows OS for example then yes, you could have used this resource on the script that runs on that node. 

I do think your requirement is valid but just not using the right resource. Maybe a cadidate for writing a custom resource or just adding something like this: https://gallery.technet.microsoft.com/scriptcenter/files-from-websites-4a181ff3

**Comment by JVimes** [comment]
Conceptually, the share is part of the node. I think you're being idealistic at the expense of usefulness. But I'm not going to keep arguing. I gave up on DSC for a few reasons, this only being one of them. Best of luck with it.

**Comment by KarolKaczmarek** [comment]
Sorry to hear that. If you would like to discuss those reasons, we would be glad to hear that. Microsoft Connect is good place for general DSC requests/bugs: https://connect.microsoft.com/PowerShell
