### ISSUE TITLE
Skip xPackage Post Validation

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xPSDesiredStateConfiguration#46]
This one might be a bit of an edge-case, but I thought I would throw it out there for discussion. It might be a feature worth adding? If not, I can implement in my own fork/repository.

The 'xPackage' resource supports installing a package where the dependency check is a registry key/value and not necessarily Add/Remove Programs. It also supports supplying credentials when running an exexcutable unlike the built-in in 'Package' resource.

I use this when deploying labs with Exchange. Running ADPrep.exe and ForestPrep.exe require domain credentials. The 'xProcess' resource doesn't cut it as I only want to run these two processes one time each - I don't want to make sure that (for example) ADPrep.exe is always running!

Unfortunately neither of these processes create a registry entry when they've been run. I use the standard 'Registry' resource to create an entry as a dependency. On the next run, the xPackage resource skips the AD and Forest prep.

However, as the exexcutables do not create a registry entry (this is created by the following resource) the post validation error (line 932 in MSFT_xPackageResource.psm1) is triggered :(.

Would it be worth adding a SkipPostValidation boolean property to the resource so if you wish to skip the post validation check, you can? This would solve my problem and maybe help others too?

Thanks, Iain

**Comment by KarolKaczmarek** [comment]
I think this is worth supporting, but perhaps instead of coupling the solution to the specific use case when we have Registry resource depending on the xProcess which creates registry key, we should add this functionality to the resource itself.

What I mean is, instead of adding SkippostValidationCheck to simply skip the validation check, we could add CreateCheckRegValue parameter which, when set to $true, would cause the xProcess resource to create this registry value after successful installation.

This way, we could enable this scenario without the need of using additional Registry resource together with adding -SkipPostValidationCheck=true to xProcess, which in my opinion is much cleaner approach.

**Comment by iainbrighton** [comment]
I get you! Are you happy for the parameter to be called 'CreateCheckRegValue'? If so, I'm happy to implement and send a pull request ;)

**Comment by KarolKaczmarek** [comment]
Sure, unless a better name comes to your mind ;) Thanks!

**Comment by iainbrighton** [comment]
@KarolKaczmarek Pull request sent for this functionality :)
