### ISSUE TITLE
Is this this thing on (who's maintaining this module)?

### ISSUE THREAD

**Issue by mhendric** [PowerShell/xPSDesiredStateConfiguration#466]
Per the below page, it doesn't look like there's any maintainers for this module. It's been over 2 months since the last Pull Request was merged, and the PR queue is falling woefully behind. Is anyone planning on taking over this role? If not, I'll volunteer to be a maintainer (or co-maintainer if anyone else wants to volunteer too).

https://github.com/PowerShell/DscResources/blob/master/Maintainers.md

Tagging @kwirkykat per above page.

**Comment by mhendric** [comment]
Can anyone comment on what's going on with this module? Is the plan to let it die? If not, can we get a new maintainer assigned, or word when we can expect someone from the PS team to work on existing PR's and Issues? @kwirkykat or @mgreenegit ?

**Comment by tmeckel** [comment]
I am really baffled how these elementary DSC modules are handled. It does not only affect this module but also its "partner module" PSDscResources. Mirosoft wants you to use the Azure DSC Automation Services in Azure, for example and also does a lot of advertising for it. But how can you justify the use with a good conscience, if you cannot rely on the quality of the offered modules, especially those which are maintained by Microsoft itself. In the current situation one can only draw the conclusion that the use of Ansible, Chef or Puppet is the far better choice.

@kwirkykat @johlju

**Comment by PlagueHO** [comment]
@kwirkykat - I'm keen to pick this module up as a maintainer (and PSDscResources) if you and @mgreenegit  are OK with it?

**Comment by tmeckel** [comment]
Now we already have two applicants. Perhaps we should award the position of maintainer in the order in which applications are received :-D But it's really sad to see the none of the people who are in charge for DSC considers it necessary to give a comment here.

**Comment by johlju** [comment]
@tmeckel Sorry for not answering, but since I left the contract position in PowerShell DSC Team, I haven't been able to catch up with the backlog (of PR's and comment in which I have been mentioned),but slowly working me there. The normal work and family takes hours away from each day. 🙂 

I agree there should be more attention to all the modules, and there was talk around this in the latest community call https://www.youtube.com/watch?v=hH2XkR-YZNQ. 
We also need more community maintainers, and two or more maintainers on a repo is only positive. Community (regardless of maintainers or contributor) discussing the issues and PR's, that is what we are missing I think. Of course there need to be at least one (community) maintainer to merge the PR's, and make sure the code follow guidelines, but it doesn't necessarily need to be a maintainer reviewing code or answering issues.

We must remember that Microsoft employees (even DSC team) are part of the community as the rest of us, and they too have a day job to keep up with. I can agree that Microsoft could have a stake in this, but couldn't that also be said of Ansible, Chef and Puppet as I think the uses the released modules as part of there offering (I could be wrong here)? 🤔 

*For reference. It is a lot of comments and PR's coming in, it took me up to 4 hours a day to just label, answering issue, review PR's and maintaining the repos, when I worked on the entire DSC Resource Kit. That did not include any coding.*

**Comment by PlagueHO** [comment]
I think just having someone from the community able to review and merge PR's in this repo will go a long way. As @johlju says, having 2 or 3 maintainers for each repo is very useful as it just spreads the load about.

But as you say, maintaining is a real time killer. So we do need more community maintainers out there to spread the load around.

Personally, I've had too many of these repos "watched" (even if I'm not maintaining) - which sometimes results in me missing or ignoring more critical issues.

I'd actually be happy dropping maintainer status on some of the other repos to pick these ones up because I see these ones being real pain points and as they are the core DSC resources they should receive the most love.

**Comment by mhendric** [comment]
I'm fine with @PlagueHO picking this up and being the lead maintainer. I'm also happy to be a co-maintainer as well. I just want to try to make sure SOMEONE is made maintainer of this...

**Comment by kwirkykat** [comment]
Done. @PlagueHO and @mhendric  sent permissions for this repo and PSDscResources.
No breaking changes in PSDscResources please.

**Comment by tmeckel** [comment]
Congrats guys @plagueho and @mhendric

**Comment by PlagueHO** [comment]
Thanks @kwirkykat . Looking forward to chipping away at these with @mhendric and of course @johlju (always top reviews :grin:)

**Comment by PlagueHO** [comment]
I reckon we can close this one now :grin: @mhendric - I'll raise an issue to update the maintainers list over in DscResorces.
