### ISSUE TITLE
TLS 1.0 needed for Pull Server to work with SQL?

### ISSUE THREAD

**Issue by Outek** [PowerShell/xPSDesiredStateConfiguration#547]
I'm trying to get a connection from a Windows Server 2019 to a SQL Database on Windows Server 2016 with MS SQL 2017, but it0s only working, as soon i activate TLS1.0. Is it possible to connect to the SQL Server using only TLS1.2? I tried different settings without success. 

This is the connection string i'm using: 

```PowerShell

<add key="dbconnectionstr" value="Provider=SQLOLEDB;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=master;Data Source=<pullservername>" />

```

also not working ist this:
```PowerShell

<add key="dbconnectionstr" value="Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=master;Data Source=<pullservername>" />

```

**Comment by mhendric** [comment]
Can you clarify where you enabled TLS 1.0 (on the Win 2019 or Win 2016 server)? Can you include a copy of your DSC configuration script? And are you positive you have the correct registry keys in place to enable TLS 1.2 on the SQL Server?

https://support.microsoft.com/en-us/help/3135244/tls-1-2-support-for-microsoft-sql-server

**Comment by pkoelemij** [comment]
I've ran into the same issue before. It's the SQLOLEDB driver that's used in the connection string of the Microsoft example that's causing the issue. The SQLOLEDB driver is legacy since SQL server 2005 and is only there for backwards compatibility. If you switch "SQLOLEDB.1" to "SQLNCLI11" it should work.

**Comment by mhendric** [comment]
> I've ran into the same issue before. It's the SQLOLEDB driver that's used in the connection string of the Microsoft example that's causing the issue.

@pkoelemij , where is the example you're referring to? Is it part of this module? Wondering if there's anything that needs to be fixed here.

**Comment by pkoelemij** [comment]
@mhendric seems that this technet article keeps popping up first when you look around for setting up a pull server with SQL for reporting:
https://blogs.technet.microsoft.com/askpfeplat/2018/07/09/configuring-a-powershell-dsc-web-pull-server-to-use-sql-database/

However, xPSDesiredStateConfiguration seems to have the sql driver right: https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/master/Examples/Sample_xDscWebServiceRegistration_UseSQLProvider.ps1

**Comment by tmeckel** [comment]
@mhendric  I agree with @pkoelemij that  the original author ran into an issue connecting to the database because inside the mentioned blog article the outdated SQL driver is used inside the connection string passed via the `SqlConnectionString` of `xDscWebService `. 

So as with you I don't see any issues here. Perhaps someone could tell the author of the Blog article that he used an outdated driver in the connection string which might cause issues.

![image](https://user-images.githubusercontent.com/14177833/52816772-47443b80-30a2-11e9-811e-3249a87c4139.png)

**Comment by mhendric** [comment]
I already reached out to the blog owners internally at Microsoft, and they're working on getting the blog updated. So as long as @Outek is happy, I think we're probably good to shut this issue down.

**Comment by tmeckel** [comment]
SGTM :-D

**Comment by Outek** [comment]
Yes, this is ok for me. The "new" string is also working for me. 
Thank you for the solution.
