### ISSUE TITLE
xService Get-TargetResource fails when service does not exist

### ISSUE THREAD

**Issue by AceHack** [PowerShell/xPSDesiredStateConfiguration#71]
Like when you are trying to ensure Absent or if the service was manually deleted.

Below is an example of a config that will fail Get

        xService RemoveService {
            Ensure = 'Absent'
            Name = 'TestService'
            DisplayName = 'TestService'
            Description = 'TestService'
            Path = 'c:\testservice.exe'
            StartupType = 'Automatic'
            State = 'Running'
        }

**Comment by kwirkykat** [comment]
Get-TargetResource should throw an error if the service does not exist.
This is by design.

This doesn't break configurations because running a configuration doesn't actually run Get-TargetResource. It will call Test-TargetResource to check if the service is compliant and then Set-TargetResource if the Test fails. Get-TargetResource is still required for resources (old design choice), but it won't actually run unless you call it in Test or Set.
