### ISSUE TITLE
Removing ComplianceServer

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/xPSDesiredStateConfiguration#93]
You're basically forcing people to not upgrade to WMF 5.
If I have a working environment based on v4, I cant enjoy any of the good things in WMF5 just bacuase theres no backward compatibility now for my ComplianceServer.

A better way would be to check if the caller is a v5 or a v4, and then enable to disable the ComplianceServer resource, no ?

**Comment by Zuldan** [comment]
I agree with Arie to some extent.

To add to his post...IsComplianceServer functions perfectly fine in WMF5. 

There are two methods in DSC 5 to register nodes and two methods to reporting. The problem is...

1. Nodes using the Configuration ID method can only be reported on by using a "Compliance Server" (IsComplianceServer).

2. Nodes using Registration Keys method can only be reported on by using a "Report Server".

Since you can only use one registration method with node and with the removal of IsComplianceServer, everyone who has their whole infrastructure setup for Configuration ID's would be forced to move to Registration Keys which should not be the case since Configuration ID's are supposed to be fully supported in PS5.

Please correct me if I'm wrong.

**Comment by NarineM** [comment]
@ArieHein,
Compliance server was reporting server for high level pull operations only. In WMF 5 we extended that functionality by introducing reporting server. You can read more about it here: https://msdn.microsoft.com/en-us/powershell/dsc/reportserver
In WMF 5 pull client supports sending detailed status reports for pull as well as push operations.

@Zuldan ,
#1 and #2 bullets in your comments section are incorrect. 
Nodes using ConfigurationID can now report to reporting server. Compliance server was extended to support push as well as detailed status reporting data from pull operations. Anyone who is using configurationID can continue using it after moving to reporting server without being forced to use registration keys.This topic talks about how to setup a node for pulling configurations from the pull server and reporting DSC operation status to reporting server using configuration ID:
https://msdn.microsoft.com/en-us/powershell/dsc/pullclientconfigid

**Comment by ArieHein** [comment]
Ok, seems like the newly updated docs make more sense now.
